In [10]:
import numpy as np
import pandas as pd

In [11]:
whr2015 = pd.read_csv("/Users/moisternw/Desktop/DSSProject/world-happiness-report/2015.csv")

In [12]:
whr2016 = pd.read_csv("/Users/moisternw/Desktop/DSSProject/world-happiness-report/2016.csv")

In [13]:
whr2017 = pd.read_csv("/Users/moisternw/Desktop/DSSProject/world-happiness-report/2017.csv")

In [14]:
energystats = pd.read_csv("/Users/moisternw/Desktop/DSSProject/international-energy-statistics/all_energy_statistics.csv")

In [15]:
energystats

,country_or_area,commodity_transaction,year,unit,quantity,quantity_footnotes,category
0,Austria,Additives and Oxygenates - Exports,1996,"Metric tons, thousand",5.00,NaN,additives_and_oxygenates
1,Austria,Additives and Oxygenates - Exports,1995,"Metric tons, thousand",17.00,NaN,additives_and_oxygenates
2,Belgium,Additives and Oxygenates - Exports,2014,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
3,Belgium,Additives and Oxygenates - Exports,2013,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
4,Belgium,Additives and Oxygenates - Exports,2012,"Metric tons, thousand",35.00,NaN,additives_and_oxygenates
5,Belgium,Additives and Oxygenates - Exports,2011,"Metric tons, thousand",25.00,NaN,additives_and_oxygenates
6,Belgium,Additives and Oxygenates - Exports,2010,"Metric tons, thousand",22.00,NaN,additives_and_oxygenates
7,Belgium,Additives and Oxygenates - Exports,2009,"Metric tons, thousand",45.00,NaN,additives_and_oxygenates
8,Czechia,Additives and Oxygenates - Exports,1998,"Metric tons, thousand",1.00,NaN,additives_and_oxygenates
9,Czechia,Additives and Oxygenates - Exports,1995,"Metric tons, thousand",7.00,NaN,additives_and_oxygenates
10,Finland,Additives and Oxygenates - Exports,2010,"Metric tons, thousand",9.00,NaN,additives_and_oxygenates
11,Finland,Additives and Oxygenates - Exports,2009,"Metric tons, thousand",13.00,NaN,additives_and_oxygenates
12,Finland,Additives and Oxygenates - Exports,2008,"Metric tons, thousand",39.00,NaN,additives_and_oxygenates
13,Finland,Additives and Oxygenates - Exports,2007,"Metric tons, thousand",21.00,NaN,additives_and_oxygenates
14,Finland,Additives and Oxygenates - Exports,2006,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
15,Finland,Additives and Oxygenates - Exports,2005,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
16,Finland,Additives and Oxygenates - Exports,2004,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
17,Finland,Additives and Oxygenates - Exports,2003,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
18,Finland,Additives and Oxygenates - Exports,2002,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
19,Finland,Additives and Oxygenates - Exports,2001,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
20,Finland,Additives and Oxygenates - Exports,2000,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
21,Finland,Additives and Oxygenates - Exports,1999,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
22,Finland,Additives and Oxygenates - Exports,1998,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
23,Finland,Additives and Oxygenates - Exports,1997,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
24,Finland,Additives and Oxygenates - Exports,1996,"Metric tons, thousand",0.00,NaN,additives_and_oxygenates
25,Finland,Additives and Oxygenates - Exports,1995,"Metric tons, thousand",3.00,NaN,additives_and_oxygenates
26,France,Additives and Oxygenates - Exports,2014,"Metric tons, thousand",119.00,NaN,additives_and_oxygenates
27,France,Additives and Oxygenates - Exports,2013,"Metric tons, thousand",102.00,NaN,additives_and_oxygenates
28,France,Additives and Oxygenates - Exports,2012,"Metric tons, thousand",62.00,NaN,additives_and_oxygenates
29,France,Additives and Oxygenates - Exports,2011,"Metric tons, thousand",55.00,NaN,additives_and_oxygenates
...,...,...,...,...,...,...,...
1189452,United States,Electricity - total wind production,1998,"Kilowatt-hours, million",3018.00,NaN,wind_electricity
1189453,United States,Electricity - total wind production,1997,"Kilowatt-hours, million",3254.00,NaN,wind_electricity
1189454,United States,Electricity - total wind production,1996,"Kilowatt-hours, million",3410.00,NaN,wind_electricity
1189455,United States,Electricity - total wind production,1995,"Kilowatt-hours, million",3196.00,NaN,wind_electricity
1189456,United States,Electricity - total wind production,1994,"Kilowatt-hours, million",3483.00,NaN,wind_electricity
1189457,United States,Electricity - total wind production,1993,"Kilowatt-hours, million",3053.00,NaN,wind_electricity
1189458,United States,Electricity - total wind production,1992,"Kilowatt-hours, million",2917.00,NaN,wind_electricity
1189459,United States,Electricity - total wind production,1991,"Kilowatt-hours, million",3051.00,NaN,wind_electricity
1189460,United States,Electricity - total wind production,1990,"Kilowatt-hours, million",3066.00,NaN,wind_electricity
1189461,Uruguay,Electricity - total wind production,2014,"Kilowatt-hours, million",732.60,NaN,wind_electricity
1189462,Uruguay,Electricity - total wind production,2013,"Kilowatt-hours, million",142.90,NaN,wind_electricity
1189463,Uruguay,Electricity - total wind production,2012,"Kilowatt-hours, million",117.80,NaN,wind_electricity
1189464,Uruguay,Electricity - total wind production,2011,"Kilowatt-hours, million",111.30,NaN,wind_electricity
1189465,Uruguay,Electricity - total wind production,2010,"Kilowatt-hours, million",69.90,NaN,wind_electricity
1189466,Uruguay,Electricity - total wind production,2009,"Kilowatt-hours, million",42.10,NaN,wind_electricity
1189467,Uruguay,Electricity - total wind production,2008,"Kilowatt-hours, million",7.30,NaN,wind_electricity
1189468,Vanuatu,Electricity - total wind production,2014,"Kilowatt-hours, million",3.00,1.0,wind_electricity
1189469,Vanuatu,Electricity - total wind production,2013,"Kilowatt-hours, million",3.00,1.0,wind_electricity
1189470,Vanuatu,Electricity - total wind production,2012,"Kilowatt-hours, million",2.90,NaN,wind_electricity
1189471,Vanuatu,Electricity - total wind production,2011,"Kilowatt-hours, million",5.00,1.0,wind_electricity
1189472,Vanuatu,Electricity - total wind production,2010,"Kilowatt-hours, million",5.17,NaN,wind_electricity
1189473,Vanuatu,Electricity - total wind production,2009,"Kilowatt-hours, million",5.63,NaN,wind_electricity
1189474,Vanuatu,Electricity - total wind production,2008,"Kilowatt-hours, million",5.63,NaN,wind_electricity
1189475,Viet Nam,Electricity - total wind production,2014,"Kilowatt-hours, million",300.00,1.0,wind_electricity
1189476,Viet Nam,Electricity - total wind production,2013,"Kilowatt-hours, million",92.00,1.0,wind_electricity
1189477,Viet Nam,Electricity - total wind production,2012,"Kilowatt-hours, million",92.00,1.0,wind_electricity
1189478,Viet Nam,Electricity - total wind production,2011,"Kilowatt-hours, million",87.00,NaN,wind_electricity
1189479,Viet Nam,Electricity - total wind production,2010,"Kilowatt-hours, million",50.00,NaN,wind_electricity
1189480,Viet Nam,Electricity - total wind production,2009,"Kilowatt-hours, million",10.00,NaN,wind_electricity
1189481,Viet Nam,Electricity - total wind production,2008,"Kilowatt-hours, million",1.00,NaN,wind_electricity